### ISSUE TITLE
Request: add glyphs for Kuni-Boazi language

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/Inconsolata#10]
From a mail sent to me

---

Hi Raph, Marc, Alexei and Kirill

Greetings from Papua New Guinea.

Thank you very much for the Inconsolata font. I just downloaded the newest version (2.001) in the hope that it might correctly render the combining diacritics we need in the Kuni-Boazi language. 
These are the combinations we use (here displayed with the Charis SIL font, if that comes out correctly on your end; see also attached text file):

```
Kuni [kvg] Unicode Test:
aeiouæɨø AEIOUÆƗØ 1234567890  
áéíóúǽɨ́ǿ ÁÉÍÓÚǼƗ́Ǿ 1́2́3́4́5́6́7́8́9́0́      (U+0300)
àèìòùæ̀ɨ̀ø̀ ÀÈÌÒÙÆ̀Ɨ̀Ø̀ 1̀2̀3̀4̀5̀6̀7̀8̀9̀0      (U+0301)
âêîôûæ̂ɨ̂ø̂ ÂÊÎÔÛÆ̂Ɨ̂Ø̂ 1̂2̂3̂4̂5̂6̂7̂8̂9̂0̂      (U+0302)
āēīōūǣɨ̄ø̄ ĀĒĪŌŪǢƗ̄Ø̄ 1̄2̄3̄4̄5̄6̄7̄8̄9̄0̄  ḡ    (U+0304)
a᷄e᷄i᷄o᷄u᷄æ᷄ɨ᷄ø᷄ A᷄E᷄I᷄O᷄U᷄Æ᷄Ɨ᷄Ø᷄ 1᷄2᷄3᷄4᷄5᷄6᷄7᷄8᷄9᷄0᷄      (U+1DC4)
a꞉e꞉i꞉o꞉u꞉ (U+A789)
```

I often need these characters in a mono-spaced version (mainly in Notepad++) but unfortunately there doesn't seem to be a mono-spaced font that handles these correctly.

This is what it looks like with the Windows Consolas font:

It's not too bad on the whole, but diacritics on digits don't work properly and the U+A789 MODIFIER LETTER COLON doesn't exist. (Yes, we do need to be able to put diacritics [in our case tone marks] on numbers. SIL's NRSI put that feature into Charis and Doulos specifically for us. I had been in contact with them for quite some time to make sure all special characters we need here in PNG get into Unicode.)

Now I was hoping that Inconsolata might do a better job, but unfortunately this is not the case. Here's what it looks like:

Missing characters are:
**U+0268 LATIN SMALL LETTER I WITH STROKE: ɨ
U+A789 MODIFIER LETTER COLON: ꞉
U+1DC4 COMBINING MACRON-ACUTE, e.g.: a᷄**

In addition, it would be nice if the rendering of the combining diacritics on digits was more accurate, but this is not as crucial at the moment. 
I realize, of course, that you are all very busy (like I am!), but it would be great if these glyphs could be added to your great Inconsolata font.

Thank you very much for considering this. 
Blessings,

Roland Fumey
SIL PNG

**Comment by rfpng** [comment]
I realise that my Charis SIL font sample didn't come out right. Here is a screenshot:
![kuni-boazi test a nfd - charis](https://cloud.githubusercontent.com/assets/29136790/26710149/3b8a1202-479b-11e7-9673-4d0fe783db39.png)

And here is the same sample using the Consolas font:
![kuni-boazi test a nfd - consolas](https://cloud.githubusercontent.com/assets/29136790/26710211/9c8ee79e-479b-11e7-84d9-3434d653d1b7.png)

And here with the Inconsolata font:
![kuni-boazi test a nfd - inconsolata](https://cloud.githubusercontent.com/assets/29136790/26710222/adb3c422-479b-11e7-8e53-cdf048b17a8e.png)

Thanks,
Roland

**Comment by rfpng** [comment]
Thanks, Dave, for your note about using the Noto Mono font, but unfortunately this doesn't work either. Here is what it looks like:
![kuni-boazi test a nfd - noto mono](https://cloud.githubusercontent.com/assets/29136790/26710574/373af182-479e-11e7-8618-30753460cab4.png)

**Comment by davelab6** [comment]
@rfpng I don't mean you should try the Noto Mono font, I mean you should take Noto Sans (assuming it works as expected) and derive from it your own "RFPNG Mono" font that is monowidth

**Comment by rfpng** [comment]
Thanks for the clarification. I'll look into that!
