### ISSUE TITLE
2.012 doesn't seem to show a monospace spacing property

### ISSUE THREAD

**Issue by nirik** [googlefonts/Inconsolata#27]
Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1634793

Folks are reporting that 2.012 doesn't show as an option in gnome-terminal, apparently due to it not showing a spacing property so it doesn't see it as a monospace font. 2.000 works fine.

**Comment by pkovacs** [comment]
The `IsFixedPitch` property appears to be set correctly in the ttf post table (that is the sentinel for monospace), but I think it's possible that fontconfig is "noticing" that there are many more widths now on various glyphs and refusing to pass this as a monospace font.   The older version of Inconsolata had one width (600) on all glyphs, but now there are widths of 0, 500, 600, 1000, etc.

**Comment by fidalgo** [comment]
With the latest OTF from master I have the problem solved, but I cannot find the 2.013 release or tag, to ask downstream (Fedora Linux) for an update.

**Comment by cprivite** [comment]
Can someone who maintains the project make a 2.013 tag please? That'd help a few of us out.

**Comment by raphlinus** [comment]
I think this will get solved by the 3.000 release, which is in PR #40. If you can locally test, that would be great, as it would also help uncover any additional possible bugs with the release.

**Comment by yaneti** [comment]
fc-scan tells me all the ttf and otf fonts in PR #40 report a spacing property of 100. Which is what we need I think. Thanks

**Comment by raphlinus** [comment]
I'm going to close this as v3.000 is out and should fix this, but please open a new issue if there are any remaining problems.
