### ISSUE TITLE
Box drawing characters width 600

### ISSUE THREAD

**Issue by raphlinus** [googlefonts/Inconsolata#36]
I'm looking at the entire character complement, and I see a lot of the box drawing glyphs have a width of 600, which is at odds with the 500 for most of the font. Does anybody know the story behind this? I'm strongly leaning towards just writing code to draw all of these, and it seems almost axiomatic to me they should have the same width as space, but I also don't want to break anything if there's a good reason for the current state.

**Comment by tracker1** [comment]
I requested support a while ago, and it was quickly added at that time.  However, I don't think it was ever properly tweaked to render correctly for sample text.

#13 and #31 which you found are a part of this.

**Comment by raphlinus** [comment]
Ah thanks. It looks like master is wrong and this is something I can fix when I redo.

**Comment by raphlinus** [comment]
This should be fixed in the v3.000 release.
