### ISSUE TITLE
How to enable ligatures in vscode

### ISSUE THREAD

**Issue by Liqiankun** [googlefonts/Inconsolata#57]
I downloaded Inconsolata from google font.
![截屏2020-08-20 21 30 54](https://user-images.githubusercontent.com/11532418/90776234-71785880-e32c-11ea-9169-56c7d69da8ee.png)
Here is my vscode settings.json file.
```json
{
  "editor.fontFamily": "Inconsolata",
  "editor.fontSize": 14,
  "editor.fontLigatures": true,
}
```
![截屏2020-08-20 21 29 38](https://user-images.githubusercontent.com/11532418/90776126-47bf3180-e32c-11ea-9122-57ed298f5ab8.png)

**Comment by hd719** [comment]
Not sure what's going on in the 3.0.0 release, but download the font (v2.012) [here](https://github.com/googlefonts/Inconsolata/releases/tag/v2.012) (Inconsolata-Regular.ttf) 

If you use vscode in this file 

`/settings.json`

```
  "editor.fontFamily": "Inconsolata",
  "editor.fontLigatures": true,
```

**Comment by Liqiankun** [comment]
@hd719 I tried it out. Not working.

**Comment by Liqiankun** [comment]
My bad! Reopen the project two. It works.

**Comment by HueyZhang** [comment]
"editor.fontLigatures": "'dlig'",
