### ISSUE TITLE
Interpolate Medium & SemiBold?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/Inconsolata#6]
Is this convenient/easy? :)

**Comment by alexeiva** [comment]
Fairly easy. But still need to check for hidden shape order incompatibilities

**Comment by m4rc1e** [comment]
The new instances are borked as you mentioned.

![screen shot 2017-03-20 at 12 13 03](https://cloud.githubusercontent.com/assets/7525512/24099354/981ef178-0d66-11e7-8e65-a3f129b68b76.png)

The master branch should always be a version of the project which is flawless. You should of ideally made these improvements in a seperate branch. Once you're happy, you'll then pr it and merge it into the master branch. 

If you pull the master branch, you get a set of fonts which have the interpolation errors shown in the screenshot. This is not good.

**Comment by alexeiva** [comment]
@m4rc1e  I've moved these commits to a `dev` branch.

**Comment by m4rc1e** [comment]
Thank you sir

**Comment by davelab6** [comment]
@appsforartists I also wonder if you would be interested in this? :D

**Comment by raphlinus** [comment]
I think we can consider this closed now that v3.000 has *much* greater coverage.
