### ISSUE TITLE
weird shapes on the terminals of some letters (s,j,J,G,r)?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/Inconsolata#7]
https://twitter.com/joseaplata/status/844605730640547840 reports a strange issue with the letter endings....

**Comment by alexeiva** [comment]
this is fixed since bffe5a9c138b25dedd1bad9332f87e470ec4e662

I need to roll back to bffe5a9c138b25dedd1bad9332f87e470ec4e662, and move the new developments commits to a dev branch. Then we can update.

**Comment by alexeiva** [comment]
done...


@m4rc1e b3ba31bc0a0934af27ffb13ccac02887d572d443 fixes this issue. Can you check and push it live?

<img width="441" alt="screen shot 2017-03-27 at 11 36 10 am" src="https://cloud.githubusercontent.com/assets/16634089/24347700/d697a3ca-12e1-11e7-8c06-ef7315b855b1.png">
<img width="458" alt="screen shot 2017-03-27 at 11 36 14 am" src="https://cloud.githubusercontent.com/assets/16634089/24347699/d6943e88-12e1-11e7-99ef-6e37a84878c0.png">

**Comment by davelab6** [comment]
@m4rc1e was this pushed?

**Comment by raphlinus** [comment]
I'm fairly certain this can be closed, the relevant version has been pushed.
